# Generated by sila2.code_generator; sila2.__version__: 0.10.1

from typing import Optional
from uuid import UUID

from sila2.server import SilaServer

from .feature_implementations.labwareautomationservice_impl import LabwareAutomationServiceImpl
from .feature_implementations.labwareontologyservice_impl import LabwareOntologyServiceImpl
from .feature_implementations.labwarequeryservice_impl import LabwareQueryServiceImpl
from .generated.labwareautomationservice import LabwareAutomationServiceFeature
from .generated.labwareontologyservice import LabwareOntologyServiceFeature
from .generated.labwarequeryservice import LabwareQueryServiceFeature


class Server(SilaServer):
    def __init__(self, server_uuid: Optional[UUID] = None):
        # TODO: fill in your server information
        super().__init__(
            server_name="TODO",
            server_type="TODO",
            server_version="0.1",
            server_description="TODO",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid,
        )

        self.labwareautomationservice = LabwareAutomationServiceImpl(self)
        self.set_feature_implementation(LabwareAutomationServiceFeature, self.labwareautomationservice)

        self.labwareontologyservice = LabwareOntologyServiceImpl(self)
        self.set_feature_implementation(LabwareOntologyServiceFeature, self.labwareontologyservice)

        self.labwarequeryservice = LabwareQueryServiceImpl(self)
        self.set_feature_implementation(LabwareQueryServiceFeature, self.labwarequeryservice)
