# dockerfile extending jupyter/base-notebook

FROM jupyter/base-notebook

# Install Python 3 packages with pip

RUN pip install --no-cache-dir sila2 && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

COPY notebooks/* /home/jovyan/work