# dockerfile extending jupyter/base-notebook

FROM jupyter/base-notebook

# Install Python 3 packages with pip

RUN pip install --no-cache-dir sila2 sparqlwrapper && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# setting default password to 'labware'
COPY jupyter_server_config.json /home/jovyan/.jupyter/jupyter_server_config.json

COPY jupyter/*_explorer.ipynb /home/jovyan/work
