# Generated by sila2.code_generator; sila2.__version__: 0.10.1
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.labwareontologyservice import CreateLabware_Responses, LabwareOntologyServiceBase

if TYPE_CHECKING:
    from ..server import Server


class LabwareOntologyServiceImpl(LabwareOntologyServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def CreateLabware(self, Name: str, *, metadata: MetadataDict) -> CreateLabware_Responses:
        raise NotImplementedError  # TODO
